monitoring_list:
  crypto:
      - BTC/USD
      - ETH/USD
      - OMG/USD
      - NKN/USD
      - DOGE/USD
      - SHIB/USD
      - SOL/USD
  nft:
    collection:
      - trippin_ape_tribe
      - okay_bears
      - degods
      - suteki
 
